CREATE DATABASE IF NOT EXISTS devbook;

USE devbook;

DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY KEY
    , name VARCHAR(64) NOT NULL
    , username VARCHAR(64) NOT NULL UNIQUE
    , email VARCHAR(64) NOT NULL UNIQUE
    , password VARCHAR(128) NOT NULL
    , created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE user_followers (
    id SERIAL PRIMARY KEY
    , user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
    , follower_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
    , UNIQUE(user_id, follower_id)
);